import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { Header } from "./_components/Header";
import ApolloProviders from "@/context/apolloProvider";
import ProdctProvider from "@/context/productProvider";
import { ThemeProvider as NextThemesProvider } from "next-themes";
import { Source_Serif_4, Sofia } from "@next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
const serif4 = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-serif",
});
const sofia = Sofia({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-sofia",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloProviders>
      <ProdctProvider>
        <html lang="en" className={`${serif4.variable} ${sofia.variable}`}>
          <body className={inter.className}>
            <NextThemesProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
            >
              <div className="w-screen flex">
                <Header />
                <main>{children}</main>
              </div>
            </NextThemesProvider>
          </body>
        </html>
      </ProdctProvider>
    </ApolloProviders>
  );
}
