import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ApolloProviders from "@/context/apolloProvider";
import ProdctProvider from "@/context/productProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ApolloProviders>
      <ProdctProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </ProdctProvider>
    </ApolloProviders>
  );
}
